<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_(ShiftF5)        Refresh</name>
   <tag></tag>
   <elementGuidId>00ac788d-56ee-4a56-8c36-6f200319c3a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTransVendPaym_9_SystemDefinedRefreshButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;LedgerJournalTransVendPaym_2_SystemDefinedRefreshButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Refresh&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c673f299-1d6a-4a6c-ac48-333c9c4e055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-serverid</name>
      <type>Main</type>
      <value>922_0</value>
      <webElementGuid>c3ddfd67-cd1f-4ea7-bdc4-449679554a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-rootserverid</name>
      <type>Main</type>
      <value>743_0</value>
      <webElementGuid>0d456dd1-adcf-4ab7-bcf8-16d8a57fb18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-controlname</name>
      <type>Main</type>
      <value>SystemDefinedRefreshButton</value>
      <webElementGuid>db2330d6-ec5e-4cca-9be6-fa1523424735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-role</name>
      <type>Main</type>
      <value>CommandButton</value>
      <webElementGuid>d4662ab7-8696-46c6-9ddc-03b403d97674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Auto button dynamicsButton</value>
      <webElementGuid>fd3e9615-592c-4211-a8fa-5910ffe3b35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a84ce4c-79ca-4f2b-9118-5df8a9b56960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
    visible: $data.Visible,
    enabled: $data.Enabled,
    click: { callBack: $data.Clicked, optOutOfAllowSave: true },
    keyDown: $data.keyDown,
    ariaPressed: $data.Toggled,
    skip: $dyn.ui.skip($data),
    superTooltip: $dyn.ui.superTooltip($data),
    attr: {
        'name': $data.Name,
        'data-dyn-button-display': $data.buttonDisplay,
    },
    sizing: $dyn.layout.sizing($data),
    css: {
        'button-isDefault' : $data.DefaultButton,
        'button-attachment-count' : $dyn.value($data.IsLabelBubble)
    }</value>
      <webElementGuid>671e5690-f184-4948-a01c-6b44d765ea7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-template-applied</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ef57e8f-e55e-4426-9e99-4cb3111d04fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>command</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>0faf939e-482d-4dc6-96fd-035abada764a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>buttonstyle</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>3505094c-de6b-4e8b-863c-d1cb788044d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>5169a0b9-55be-4ab6-8d9d-1412914bc70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-optional-label</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>5480232c-f5b3-409c-8b54-ef740abaa7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTransVendPaym_9_SystemDefinedRefreshButton</value>
      <webElementGuid>eb7ef7ea-419d-4f97-9cde-9f4e0d87bc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-lastvisible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d970dfa-57df-4e43-b842-c04ab9904140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c4caefcc-8afc-4eef-9f1b-05f7fa994adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9de4eb59-8c23-4990-9430-949b5c0c745f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SystemDefinedRefreshButton</value>
      <webElementGuid>cf230a14-cab0-42f9-a171-c211a0742d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-button-display</name>
      <type>Main</type>
      <value>ImageOnly</value>
      <webElementGuid>44042e23-022b-4936-9a62-b7411485ea06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>superToolTip</value>
      <webElementGuid>c3fbbcb1-de62-4a9b-949b-21103c80a1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
        (Shift+F5)
        Refresh
    </value>
      <webElementGuid>3908beb4-ac25-4612-94ba-4fa6fc6899fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTransVendPaym_9_SystemDefinedRefreshButton&quot;)</value>
      <webElementGuid>7ba0154d-1616-468a-a19d-a02c95e2e77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-superToolTip</value>
      <webElementGuid>882218eb-0869-4d8a-8c91-374f1b995cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LedgerJournalTransVendPaym_9_SystemDefinedRefreshButton']</value>
      <webElementGuid>f5787a79-aa36-48b2-980a-0a2b4795aee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTransVendPaym_9_SystemDefinedButtonsButtonGroup_Form']/button[2]</value>
      <webElementGuid>8d985e6e-96a6-4fcf-b522-1f14ab64f81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in Microsoft Office'])[2]/following::button[2]</value>
      <webElementGuid>7a4b7ae2-9478-4f27-80cd-592274c5da5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button[2]</value>
      <webElementGuid>abfd3e0d-6000-4227-8235-03512ff316f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'LedgerJournalTransVendPaym_9_SystemDefinedRefreshButton' and @name = 'SystemDefinedRefreshButton' and (text() = '
        
        (Shift+F5)
        Refresh
    ' or . = '
        
        (Shift+F5)
        Refresh
    ')]</value>
      <webElementGuid>97036e14-9a03-4cd7-ba86-7c19b5db2190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LedgerJournalTransVendPaym_3_SystemDefinedRefreshButton']</value>
      <webElementGuid>3cf26671-0484-4ae5-a5e5-85db57038e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTransVendPaym_3_SystemDefinedButtonsButtonGroup_Form']/button[2]</value>
      <webElementGuid>6898e118-7b94-4c62-aabc-d4f6459ac223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'LedgerJournalTransVendPaym_3_SystemDefinedRefreshButton' and @name = 'SystemDefinedRefreshButton' and (text() = '
        
        (Shift+F5)
        Refresh
    ' or . = '
        
        (Shift+F5)
        Refresh
    ')]</value>
      <webElementGuid>953a5dd3-7c07-4549-b65d-184b83f67bd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
