<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_(AltEnter)        OK</name>
   <tag></tag>
   <elementGuidId>79b57276-35c6-4124-87f1-5e2496e9a149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dialog_5_OkButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Dialog_5_OkButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e544f37-4a4c-4053-a56a-37c08e79866f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-serverid</name>
      <type>Main</type>
      <value>601_0</value>
      <webElementGuid>c8be0dbc-fde1-4457-ae98-fd6155bbabed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-rootserverid</name>
      <type>Main</type>
      <value>586_0</value>
      <webElementGuid>da2dc1c4-2628-471d-85ae-b6db66c26670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-controlname</name>
      <type>Main</type>
      <value>OkButton</value>
      <webElementGuid>9fef09aa-dcce-42ea-8faa-cbc1b2a495a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-role</name>
      <type>Main</type>
      <value>CommandButton</value>
      <webElementGuid>f843e6e1-2f23-47ae-a455-c6692986b4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Auto button dynamicsButton button-isDefault</value>
      <webElementGuid>07395684-c927-4bc8-b932-001b20206890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae4c343b-9f72-4dea-b405-33cd850f0a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
    visible: $data.Visible,
    enabled: $data.Enabled,
    click: { callBack: $data.Clicked, optOutOfAllowSave: true },
    keyDown: $data.keyDown,
    ariaPressed: $data.Toggled,
    skip: $dyn.ui.skip($data),
    superTooltip: $dyn.ui.superTooltip($data),
    attr: {
        'name': $data.Name,
        'data-dyn-button-display': $data.buttonDisplay,
    },
    sizing: $dyn.layout.sizing($data),
    css: {
        'button-isDefault' : $data.DefaultButton,
        'button-attachment-count' : $dyn.value($data.IsLabelBubble)
    }</value>
      <webElementGuid>a5b19cc3-c31f-4350-8ecd-0c5280ef53c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-template-applied</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93f3f812-ab53-4480-8013-9fa23bb081dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>buttonstyle</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>73e5dbcd-bc00-4e9d-8c04-fc778c74e004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dialog_5_OkButton</value>
      <webElementGuid>c2abb8a1-8e81-4b68-8c7e-3b5ec1ee74a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-lastvisible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>574612d4-100b-4757-bbef-57cdec3a04fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eee03f51-9eb4-416b-ac5c-cf79fb672e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60245679-2c82-4f16-b7ea-f8497f6b55c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OkButton</value>
      <webElementGuid>bbd9bb6c-221e-4af8-861f-b1df90befbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-button-display</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>fc91fd5e-8210-48f0-aab8-a2d7cc702e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>superToolTip</value>
      <webElementGuid>7a105843-0a75-4096-b9e6-57366959e869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-superToolTip</value>
      <webElementGuid>6e04a57f-ecfa-4cff-ba0d-1182a380bde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
        (Alt+Enter)
        OK
    </value>
      <webElementGuid>ec04385a-bda4-4d2d-93f2-7921f889db12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dialog_5_OkButton&quot;)</value>
      <webElementGuid>25daf28c-7df8-4023-841f-7e45162746b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Dialog_5_OkButton']</value>
      <webElementGuid>3c71d444-e449-496f-aecb-60850411cb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dialog_5_BottomButtonGrp']/div[2]/button</value>
      <webElementGuid>54c8506b-b127-44c3-b380-aa206c73ebf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Records to include'])[1]/following::button[1]</value>
      <webElementGuid>9d66a1c1-3e47-4d06-ba12-408d21064261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='After the lookup is open, you can use Alt+Down to move focus into the lookup.'])[4]/following::button[2]</value>
      <webElementGuid>6c316e70-58b5-4f05-8f8f-7c1477baab21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>d162bd05-3eca-48b7-a807-cd43e2c8fc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'Dialog_5_OkButton' and @name = 'OkButton' and (text() = '
        
        (Alt+Enter)
        OK
    ' or . = '
        
        (Alt+Enter)
        OK
    ')]</value>
      <webElementGuid>c646cc85-bd2a-49af-bf92-120af01e521d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
