<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_(Esc)        Back</name>
   <tag></tag>
   <elementGuidId>7e6e2fd9-4e75-49fc-916c-0249334cbf7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTransVendPaym_10_SystemDefinedCloseButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;LedgerJournalTransVendPaym_3_SystemDefinedCloseButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Back&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f537aef-e9d4-4470-aee6-6d42e30dedc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-serverid</name>
      <type>Main</type>
      <value>905_0</value>
      <webElementGuid>9c8ae6e0-1f42-455a-9a13-8820ddba1247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-rootserverid</name>
      <type>Main</type>
      <value>743_0</value>
      <webElementGuid>47da4c8f-52fb-487f-bf02-4fddb90bef66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-controlname</name>
      <type>Main</type>
      <value>SystemDefinedCloseButton</value>
      <webElementGuid>4a6d3212-90ac-4705-ace3-fe2761bc09c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-role</name>
      <type>Main</type>
      <value>CommandButton</value>
      <webElementGuid>adb53bd3-9eb9-46a4-8ff5-d06895e45385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Auto button dynamicsButton</value>
      <webElementGuid>c4c11874-32a0-4de6-a49f-9eb289700970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fdc7e5dc-ee58-499e-bc2a-c6fcf69d938c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
    visible: $data.Visible,
    enabled: $data.Enabled,
    click: { callBack: $data.Clicked, optOutOfAllowSave: true },
    keyDown: $data.keyDown,
    ariaPressed: $data.Toggled,
    skip: $dyn.ui.skip($data),
    superTooltip: $dyn.ui.superTooltip($data),
    attr: {
        'name': $data.Name,
        'data-dyn-button-display': $data.buttonDisplay,
    },
    sizing: $dyn.layout.sizing($data),
    css: {
        'button-isDefault' : $data.DefaultButton,
        'button-attachment-count' : $dyn.value($data.IsLabelBubble)
    }</value>
      <webElementGuid>0bdc3cab-4cf7-40ce-84fd-3f21460678c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-template-applied</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e8812e5e-720d-4e41-920d-dab8002acb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>command</name>
      <type>Main</type>
      <value>PreviousView</value>
      <webElementGuid>2463307b-e904-4831-8139-47c2e7223ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>buttonstyle</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>ac691b5a-0729-4bd1-9e8e-599051b844da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>e86feb75-7569-40f3-96f8-5b9896bfe0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-optional-label</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>ed0f8a59-72ee-462e-89e5-68720cb68543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTransVendPaym_10_SystemDefinedCloseButton</value>
      <webElementGuid>d08c6a75-e85b-4fb4-8ad9-27f2d1188779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-lastvisible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>515a26b3-e6eb-4432-9180-eb2f73c93b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fdc82bef-963d-45fb-a6db-4bf643aa5028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>071514be-19ea-4541-b505-2619be314d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SystemDefinedCloseButton</value>
      <webElementGuid>d15a17e9-74dc-47e2-b6ee-3e6a2d7d6fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-button-display</name>
      <type>Main</type>
      <value>ImageOnly</value>
      <webElementGuid>8e376370-063a-4159-96d4-a348bf90ee77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>superToolTip</value>
      <webElementGuid>7c2db0bb-94ce-4af0-90e7-9ce35624f9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
        (Esc)
        Back
    </value>
      <webElementGuid>fd22daff-f371-4abc-819b-82a931331002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTransVendPaym_10_SystemDefinedCloseButton&quot;)</value>
      <webElementGuid>66f82ffb-c817-496a-8349-d565e15f560f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-superToolTip</value>
      <webElementGuid>5cf58a42-1322-420e-a387-23a39d121883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LedgerJournalTransVendPaym_10_SystemDefinedCloseButton']</value>
      <webElementGuid>301bc820-538d-4ab2-9870-f7a981df11b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTransVendPaym_10_SysCloseGroup']/button</value>
      <webElementGuid>8908bff8-0bb2-4bf8-8126-4e2e798d1ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Related information'])[2]/following::button[1]</value>
      <webElementGuid>de228a25-e5fb-443a-adc7-fb9cc37df8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rejected by'])[1]/following::button[2]</value>
      <webElementGuid>f7dd61ac-dff6-4ec8-a3bd-55e1929c440a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[3]/div/div[2]/button</value>
      <webElementGuid>9655560d-ab2b-4d22-80b5-262b17394c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'LedgerJournalTransVendPaym_10_SystemDefinedCloseButton' and @name = 'SystemDefinedCloseButton' and (text() = '
        
        (Esc)
        Back
    ' or . = '
        
        (Esc)
        Back
    ')]</value>
      <webElementGuid>02c4f7d2-891a-44af-89f8-cf4be5efec98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LedgerJournalTransVendPaym_8_SystemDefinedCloseButton']</value>
      <webElementGuid>6482f8d9-7a61-4384-afeb-e62c790a456d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTransVendPaym_8_SysCloseGroup']/button</value>
      <webElementGuid>f494a51d-6673-4752-9ccb-9bb6abc15564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'LedgerJournalTransVendPaym_8_SystemDefinedCloseButton' and @name = 'SystemDefinedCloseButton' and (text() = '
        
        (Esc)
        Back
    ' or . = '
        
        (Esc)
        Back
    ')]</value>
      <webElementGuid>319d0e6d-9c73-4bdc-94aa-c454b3355036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LedgerJournalTransVendPaym_3_SystemDefinedCloseButton']</value>
      <webElementGuid>4f43c0fd-0335-4062-88e5-322d1cd40b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTransVendPaym_3_SysCloseGroup']/button</value>
      <webElementGuid>f4753eff-9cb6-428a-a091-8c76dc3eafd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postprocess operation completed'])[1]/following::button[5]</value>
      <webElementGuid>c7bae78a-c355-4f6e-8a20-90cb2cd45d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment generation process information'])[1]/following::button[5]</value>
      <webElementGuid>256d53da-8a95-4a96-b852-74107d1e99fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'LedgerJournalTransVendPaym_3_SystemDefinedCloseButton' and @name = 'SystemDefinedCloseButton' and (text() = '
        
        (Esc)
        Back
    ' or . = '
        
        (Esc)
        Back
    ')]</value>
      <webElementGuid>f2b66dfa-25a5-418b-a968-8d63f2d0451d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LedgerJournalTransVendPaym_4_SystemDefinedCloseButton']</value>
      <webElementGuid>1554ee8e-48da-4af3-bd4f-667603c18ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTransVendPaym_4_SysCloseGroup']/button</value>
      <webElementGuid>0abb5ee4-9ad6-4fde-b657-1ef108eb5166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'LedgerJournalTransVendPaym_4_SystemDefinedCloseButton' and @name = 'SystemDefinedCloseButton' and (text() = '
        
        (Esc)
        Back
    ' or . = '
        
        (Esc)
        Back
    ')]</value>
      <webElementGuid>b9d8cb91-97b6-44a2-873f-2cfa1da7e6e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
