<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_(AltS)        Save</name>
   <tag></tag>
   <elementGuidId>25afb491-6f27-47dd-80de-6e3f3057323c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='LedgerJournalTransVendPaym_3_SystemDefinedSaveButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTransVendPaym_3_SystemDefinedSaveButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62f78877-6d6b-427d-a947-1fbca3982035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-serverid</name>
      <type>Main</type>
      <value>495_0</value>
      <webElementGuid>0cd05054-32a0-4342-bb3c-26ae57b231eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-rootserverid</name>
      <type>Main</type>
      <value>303_0</value>
      <webElementGuid>093f6a36-fb0e-4019-8f86-062a472c6042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-controlname</name>
      <type>Main</type>
      <value>SystemDefinedSaveButton</value>
      <webElementGuid>e9e482e1-f691-497f-bd7b-8c1637f9d276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-role</name>
      <type>Main</type>
      <value>CommandButton</value>
      <webElementGuid>6b709d9f-bf94-426f-9da9-703913677d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Auto button dynamicsButton</value>
      <webElementGuid>75f68ed1-a211-453a-a555-8548cfbcd7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef85bc50-88b4-47bc-a54b-890c5bded7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
    visible: $data.Visible,
    enabled: $data.Enabled,
    click: { callBack: $data.Clicked, optOutOfAllowSave: true },
    keyDown: $data.keyDown,
    ariaPressed: $data.Toggled,
    skip: $dyn.ui.skip($data),
    superTooltip: $dyn.ui.superTooltip($data),
    attr: {
        'name': $data.Name,
        'data-dyn-button-display': $data.buttonDisplay,
    },
    sizing: $dyn.layout.sizing($data),
    css: {
        'button-isDefault' : $data.DefaultButton,
        'button-attachment-count' : $dyn.value($data.IsLabelBubble)
    }</value>
      <webElementGuid>f75e722b-d4d7-4aa0-a882-4beb797eba23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-template-applied</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2d9d86f-24ec-49bf-b48d-969c236f5de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>buttonstyle</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>260c28c3-78d2-4ef0-bb48-704f0577a09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTransVendPaym_3_SystemDefinedSaveButton</value>
      <webElementGuid>b62c24b7-231a-48fd-a4ac-4fd9914671de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-lastvisible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e44a0d2f-1287-4c10-8700-b85a4597796a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8bd81abc-a0bb-4eb0-845c-20413450f374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3191e185-0ef3-4352-a0c0-4b313d7bf27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SystemDefinedSaveButton</value>
      <webElementGuid>22c9b8c6-4344-4e76-97f1-11e550622d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-button-display</name>
      <type>Main</type>
      <value>TextWithImageLeft</value>
      <webElementGuid>15e611db-a364-4434-be51-d70028bf26d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>superToolTip</value>
      <webElementGuid>8aa590c6-df89-4e7a-a8e1-611824145adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-superToolTip</value>
      <webElementGuid>a0feca54-7d9c-4a51-8440-1e74a1ec1a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
        (Alt+S)
        Save
    </value>
      <webElementGuid>1e9b0ec5-96b1-49ea-bc0f-c9601e4e50ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTransVendPaym_3_SystemDefinedSaveButton&quot;)</value>
      <webElementGuid>fb4815a3-2f9d-4a8c-9116-c7232b676d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LedgerJournalTransVendPaym_3_SystemDefinedSaveButton']</value>
      <webElementGuid>1a7c5576-14f6-4071-8731-ef87edebf635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTransVendPaym_3_SystemDefinedPage']/button</value>
      <webElementGuid>2db9e739-431c-4320-bbfc-7d82b63c6af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/following::button[1]</value>
      <webElementGuid>c7cbc5fd-2dbe-496f-9df2-d780a91b6777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Esc)'])[2]/following::button[1]</value>
      <webElementGuid>adb1ae9f-e5bb-4875-9722-a3f335003164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[3]/div/div[3]/button</value>
      <webElementGuid>25d6bfb3-7a84-4aa8-886c-925b80009eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'LedgerJournalTransVendPaym_3_SystemDefinedSaveButton' and @name = 'SystemDefinedSaveButton' and (text() = '
        
        (Alt+S)
        Save
    ' or . = '
        
        (Alt+S)
        Save
    ')]</value>
      <webElementGuid>9bf0637a-826d-4d8f-a1e4-424397224fc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
