<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_(AltEnter)        OK_1_2</name>
   <tag></tag>
   <elementGuidId>1f546a4d-2f5b-4d57-a3d6-a011d7e8b76f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SysOperationTemplateForm_15_CommandButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Dialog_10_OkButton&quot;]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>144ec301-1711-4dca-b918-e6711f0b3715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-serverid</name>
      <type>Main</type>
      <value>1099_0</value>
      <webElementGuid>e7c3a691-283d-4b3a-8e66-f7d3a91d3944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-rootserverid</name>
      <type>Main</type>
      <value>1076_0</value>
      <webElementGuid>96a41c55-e8bf-4e44-a05e-3d12716c1fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-controlname</name>
      <type>Main</type>
      <value>CommandButton</value>
      <webElementGuid>a8e02dd2-94b4-4b49-a92b-971b934bf151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-role</name>
      <type>Main</type>
      <value>CommandButton</value>
      <webElementGuid>45636cbe-c3f7-4cdc-8b22-4899e57ba790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Auto button dynamicsButton button-isDefault</value>
      <webElementGuid>95cdbe71-e5de-479a-bb16-e86e613fb49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a57f77d-6698-4b4e-a17d-a7da765f3d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
    visible: $data.Visible,
    enabled: $data.Enabled,
    click: { callBack: $data.Clicked, optOutOfAllowSave: true },
    keyDown: $data.keyDown,
    ariaPressed: $data.Toggled,
    skip: $dyn.ui.skip($data),
    superTooltip: $dyn.ui.superTooltip($data),
    attr: {
        'name': $data.Name,
        'data-dyn-button-display': $data.buttonDisplay,
    },
    sizing: $dyn.layout.sizing($data),
    css: {
        'button-isDefault' : $data.DefaultButton,
        'button-attachment-count' : $dyn.value($data.IsLabelBubble)
    }</value>
      <webElementGuid>1a58b7cd-003b-46e0-a35f-4c71b3814d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-template-applied</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f175ece-a9b5-405c-8cc1-c112cb7ee330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>buttonstyle</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>5eb235d4-cb15-4f4b-b1bd-548727853a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SysOperationTemplateForm_15_CommandButton</value>
      <webElementGuid>4854e74d-e4f2-4300-8601-ee476712950f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-lastvisible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e652bf88-369c-4f3f-99f4-480f8ea5e2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3320e594-f6c9-4afd-8d11-5ce84824b377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2eff4a76-aebd-4a8c-a9f1-2bc28ae81d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CommandButton</value>
      <webElementGuid>d36f7deb-747a-4fc9-8837-a3eaafb9844e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-button-display</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>3a008cb6-3ba9-41fa-8540-4866669c2514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>superToolTip</value>
      <webElementGuid>27ae20d1-9e8d-4c01-b9ec-9ecb7d4881e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-superToolTip</value>
      <webElementGuid>2f7bd1c0-7e90-4a19-aea0-0664ea89b538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
        (Alt+Enter)
        OK
    </value>
      <webElementGuid>c7f0d605-ba84-445b-91dc-ab22076e028d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SysOperationTemplateForm_15_CommandButton&quot;)</value>
      <webElementGuid>9dade10c-fc7f-4b22-b991-1067f8fe174e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='SysOperationTemplateForm_15_CommandButton']</value>
      <webElementGuid>f69810d2-0ccf-4983-b666-c771d9b670e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SysOperationTemplateForm_15_BottomButtonGrp']/div[2]/button</value>
      <webElementGuid>89023be6-9310-4200-b2ce-1ba91a35e351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Run in the background'])[1]/following::button[1]</value>
      <webElementGuid>bbc4f7b5-06f7-475e-a2ae-f6c3341bf028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/following::button[2]</value>
      <webElementGuid>8246e7cf-ce91-4350-afc2-bee4ce6ac7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>868214d7-9a18-40c2-b4ef-9272afd30397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'SysOperationTemplateForm_15_CommandButton' and @name = 'CommandButton' and (text() = '
        
        (Alt+Enter)
        OK
    ' or . = '
        
        (Alt+Enter)
        OK
    ')]</value>
      <webElementGuid>89279496-507a-4d98-84c2-70147de59bc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
