<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DateVoucherCompanyAccountVendor nameFin_31ebec</name>
   <tag></tag>
   <elementGuidId>5633a65d-759c-4898-a034-d78d202707e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overviewGrid_303_0_grid']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#overviewGrid_303_0_grid > div.fixedDataTableLayout_rowsContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#overviewGrid_303_0_grid > .fixedDataTableLayout_rowsContainer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e58e3e7-6962-499f-b7e6-6157bb647e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixedDataTableLayout_rowsContainer</value>
      <webElementGuid>24486eae-cef8-4fc5-b7a3-488be4529ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DateVoucherCompanyAccountVendor nameFinancial tagsDescriptionDebitCreditCurrencyBank accountOffset account typeOffset accountOffset financial tagsMethod of paymentPayment statusCheck numberPayment request idSegmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.</value>
      <webElementGuid>ccb6cfd7-a91b-4c59-a13f-acf490854229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overviewGrid_303_0_grid&quot;)/div[@class=&quot;fixedDataTableLayout_rowsContainer&quot;]</value>
      <webElementGuid>6e07861b-a843-4ecd-b064-51520b61b3de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overviewGrid_303_0_grid']/div</value>
      <webElementGuid>11808238-0740-44ef-bbd1-e49c37d0bfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View marked transactions'])[1]/following::div[8]</value>
      <webElementGuid>fedc505d-7bd5-4370-a932-af1cf0a29754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voucher'])[1]/following::div[9]</value>
      <webElementGuid>5274ee95-ae0e-4580-adf9-4b7f05b389e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>b623d5ab-4aa0-48a8-b7e9-35cf8b89bde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DateVoucherCompanyAccountVendor nameFinancial tagsDescriptionDebitCreditCurrencyBank accountOffset account typeOffset accountOffset financial tagsMethod of paymentPayment statusCheck numberPayment request idSegmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.' or . = 'DateVoucherCompanyAccountVendor nameFinancial tagsDescriptionDebitCreditCurrencyBank accountOffset account typeOffset accountOffset financial tagsMethod of paymentPayment statusCheck numberPayment request idSegmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.Segmented Entry control. Type values for the segments. If lookup is closed, use enter, arrow keys, or chart of accounts delimiter to move segments. Tab to exit the field. Alt+Down opens the list of values.  When lookup is open, use up and down arrows, page up or down, or home and end to move through list. Press enter to select a value and advance a segment. Pressing Alt+Down twice moves focus to the flyout and its segments. Pressing Alt+W changes the show all and show valid filter.')]</value>
      <webElementGuid>7a8bcd2c-a9a6-4e51-ac24-30c4f9c8de2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
