<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_AutoLookup_AccountID_603_0_1_input</name>
   <tag></tag>
   <elementGuidId>3fa14e3f-eaa7-4dca-948f-d736fb1d3abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AutoLookup_AccountID_603_0_1_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AutoLookup_AccountID_603_0_1_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AutoLookup_AccountID_603_0_1_input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a39f99ba-573e-4589-8fe4-6176ccbda44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AutoLookup_AccountID_603_0_1_input</value>
      <webElementGuid>92d0572d-4d3b-4f44-9f04-548e8647e348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>14b2b701-4d54-4513-a6a8-51d76692f67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc1a52f9-58cb-49d5-b155-0afe5c1f3bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ced692ff-2571-4f44-84c7-355a5aeb8583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Bank account</value>
      <webElementGuid>3119f080-64eb-458f-a4c8-42f46ad5346e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _tqmjor</value>
      <webElementGuid>f22e40af-c2fb-42ef-ba5b-ce9e5d20ae13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3d324ffc-1263-4a80-965a-4ebb2f130e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ISA_CODA</value>
      <webElementGuid>2db88753-5df8-4669-8af5-22a971437c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-savedtooltip</name>
      <type>Main</type>
      <value>ISA_CODA</value>
      <webElementGuid>26a3b379-9f60-4b90-af66-2e983b281e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-previewenabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64422d3b-9fd6-4148-a79c-fc7bb44fe031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AutoLookup_AccountID_603_0_1_input&quot;)</value>
      <webElementGuid>2a6ee59b-5ec7-4695-80eb-56ce5992f0f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AutoLookup_AccountID_603_0_1_input']</value>
      <webElementGuid>ea42a8c7-a15f-4a76-8ab3-412ecf2a2853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AutoLookup_AccountID_603_0_1']/div/input</value>
      <webElementGuid>f28773f3-d1d9-4cc3-9e27-8e5f61e0b74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>752ae781-e107-4d1e-87d8-e93a9716f6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AutoLookup_AccountID_603_0_1_input' and @type = 'text']</value>
      <webElementGuid>7b33b426-06d0-47ff-8ec5-1e504b145b13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
