<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment request id_LedgerJournalTrans_ac2578</name>
   <tag></tag>
   <elementGuidId>629af905-3b50-429b-8dfb-8445dc32223d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'LedgerJournalTrans_PaymentStatus_115_0_0_input' and @type = 'text' and @title = 'Sent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTrans_PaymentStatus_115_0_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;LedgerJournalTrans_PaymentStatus_303_0_0_input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Select or unselect row The row is up to date. Date Open Voucher Company Account Vendor name Description Open Debit Credit Currency Bank account Offset account type Offset account Method of payment Payment status Check number Payment request id&quot;i] >> internal:label=&quot;Payment status&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5179c03f-3e6c-444c-a092-a82563174ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTrans_PaymentStatus_115_0_0_input</value>
      <webElementGuid>96a304c7-13a4-4c6c-bc5f-c7b0179227cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c77c05b0-71a2-41f1-98bf-d49c4f0bc395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47a227e2-eec6-456b-b8d0-16a836f732f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ede895d4-4c77-4edd-b303-24e299eb57f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Payment status</value>
      <webElementGuid>2b813d0e-5ec3-4495-8514-96e7a2bd66e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _ezcqi5</value>
      <webElementGuid>e6569d71-97a9-46ea-b811-68cacf7679a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>04e83b2b-e1cb-409a-8de7-8678a251c484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>a3320e68-f918-4f2b-a9f3-e4ad26efa496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTrans_PaymentStatus_115_0_0_input&quot;)</value>
      <webElementGuid>a62b641e-c567-411c-9a6f-2c8874ce4800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LedgerJournalTrans_PaymentStatus_115_0_0_input']</value>
      <webElementGuid>bce10a44-a04e-4fa1-89ab-54abac1eeec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTrans_PaymentStatus_115_0_0']/div/input</value>
      <webElementGuid>145ce6ae-b47a-44fb-89d0-7b09df387dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/div/div/div/input</value>
      <webElementGuid>9424b721-7d80-4598-bf41-8af2fb82d7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LedgerJournalTrans_PaymentStatus_115_0_0_input' and @type = 'text' and @title = 'Sent']</value>
      <webElementGuid>a4af2651-fc39-4fac-b5c1-a872479ffb06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
