<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_AutoLookup_AccountID_1052_0_4_input</name>
   <tag></tag>
   <elementGuidId>dfb83e4f-86a7-43f1-a923-6c27522d0ec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AutoLookup_AccountID_1052_0_4_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AutoLookup_AccountID_1052_0_4_input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a11c4a8-db49-4438-ad03-b92879e96bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AutoLookup_AccountID_1052_0_4_input</value>
      <webElementGuid>fd1d726f-bc2f-4da1-9998-0948bcf067a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4685f7fc-f752-45be-a1a1-7590f6e8c857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d225dbfb-950e-4a05-a41a-0a54e783756f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ae42e4d-376e-4fae-bb94-d21e4a3869ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Bank account</value>
      <webElementGuid>ecf133ad-21b7-4fa3-a05a-1d749605692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _tqmjor</value>
      <webElementGuid>01aa0332-b0a8-4fd6-a69a-b0dcfbd5d358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ISA_CODA</value>
      <webElementGuid>4dbecdb7-8d18-41b9-bfc0-bff5a96a3037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-savedtooltip</name>
      <type>Main</type>
      <value>ISA_CODA</value>
      <webElementGuid>e73dd259-4a82-46af-b699-e48932659569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-previewenabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>55f6e827-1989-4736-989e-99437b953565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AutoLookup_AccountID_1052_0_4_input&quot;)</value>
      <webElementGuid>c2bd2682-f6b4-4031-85ce-54a4e1c8c0e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AutoLookup_AccountID_1052_0_4_input']</value>
      <webElementGuid>648550d8-fb84-496f-8a84-d81ab176b293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AutoLookup_AccountID_1052_0_4']/div/input</value>
      <webElementGuid>6f5fdab6-7056-4939-8978-b3642cb08054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>1d9c20e1-d38b-4d9e-9ccd-9a217690e2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AutoLookup_AccountID_1052_0_4_input' and @type = 'text']</value>
      <webElementGuid>e4bf99ef-8f22-4bf2-aacb-f4316a8be738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
