<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment request id_LedgerJournalTrans_df9748</name>
   <tag></tag>
   <elementGuidId>9ec539e7-4480-4f5c-9140-d2d69f891f6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTrans_PaymentStatus_303_0_1_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;LedgerJournalTrans_PaymentStatus_303_0_1_input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Select or unselect row The row is up to date. Date Voucher Company Account Vendor name Description Debit Credit Currency Bank account Offset account type Offset account Method of payment Payment status Check number Payment request id&quot;i] >> internal:label=&quot;Payment status&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c21f9dd8-6afd-4094-b120-808e2ce27662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTrans_PaymentStatus_303_0_1_input</value>
      <webElementGuid>a9a7f4fb-2841-48c7-9822-b407b5c50905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8ab9c6dc-03c7-439d-8c9c-a545ee5bff1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd8598cf-62ab-4aa9-8eac-f60dd0851014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b45ab439-35e5-4479-8402-e722b4ca3ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Payment status</value>
      <webElementGuid>09e8d622-5bbc-4159-8180-e695860449aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _ezcqi5</value>
      <webElementGuid>44161793-0e8e-4b8d-a9c4-c22aec75d10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>c879e185-f869-4d4a-8dc3-11b4f8166850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a83b5935-d29d-43eb-89f3-5e9bc21398c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>5798394d-b352-4305-ae84-a4ff8df28e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTrans_PaymentStatus_303_0_1_input&quot;)</value>
      <webElementGuid>6adf657b-2d74-41a6-a79d-ab1ed3c3e5d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LedgerJournalTrans_PaymentStatus_303_0_1_input']</value>
      <webElementGuid>ae2d3ddf-4139-42a9-a4f0-529c47ce4742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTrans_PaymentStatus_303_0_1']/div/input</value>
      <webElementGuid>ddde2f22-6c4e-4642-ac69-764c00f917cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[16]/div/div/div/div/div/div/input</value>
      <webElementGuid>2a517a94-b7f6-4708-b48a-5ad03da05ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LedgerJournalTrans_PaymentStatus_303_0_1_input' and @type = 'text' and @title = 'Sent']</value>
      <webElementGuid>9fc04784-10be-4a96-af01-63ef7a99b4f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
