<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment request id_LedgerJournalTrans_f27213</name>
   <tag></tag>
   <elementGuidId>3bd214f8-d89b-448c-b084-0439f819dd3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTrans_PaymentStatus_586_0_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;LedgerJournalTrans_PaymentStatus_743_0_1_input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Select or unselect row The row is up to date. Date Voucher Company Account Vendor name Description Open Debit Credit Currency Bank account Offset account type Offset account Method of payment Payment status Check number Payment request id&quot;i] >> internal:label=&quot;Payment status&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4d20d90-15e0-40f0-b82c-2bfbd4d14662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTrans_PaymentStatus_586_0_0_input</value>
      <webElementGuid>2460b7dd-adbd-4ee6-a409-ad9d315a58fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>96b41b85-8fac-470b-94bd-29b80b1a6859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>472df913-3736-497d-8751-07f32cd9fc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>200c7852-4e4e-4fe8-a5a6-1b009d176083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Payment status</value>
      <webElementGuid>f8300962-1276-4137-8b0e-2d773b5a8bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _ezcqi5</value>
      <webElementGuid>0f4b574c-0e25-4745-a709-977afeaeee2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>0f938e51-6b5c-42b9-809e-e405b8f24ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>97d2ef8c-e545-4fbd-8535-48a87b77644c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTrans_PaymentStatus_586_0_0_input&quot;)</value>
      <webElementGuid>d78e6435-8548-4953-bd86-524d192721aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LedgerJournalTrans_PaymentStatus_586_0_0_input']</value>
      <webElementGuid>2996c67f-224e-42c0-8c21-1c943265dce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTrans_PaymentStatus_586_0_0']/div/input</value>
      <webElementGuid>040b9e66-8471-4bd4-ba2c-621d4f4e5d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/div/div/div/input</value>
      <webElementGuid>08381598-9570-439c-a60f-b47c08240375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LedgerJournalTrans_PaymentStatus_586_0_0_input' and @type = 'text' and @title = 'Sent']</value>
      <webElementGuid>3379f75b-ff75-4db8-b6e2-bad796dc3e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
