<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment request id_LedgerJournalTrans_1e64f4</name>
   <tag></tag>
   <elementGuidId>0093df2d-b60b-4994-b4ac-38b8ddc6b61f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[16]/div/div/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTrans_PaymentStatus_735_0_0_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Select or unselect row The row is up to date. Date Voucher Company Account Vendor name Description Open Debit Credit Currency Bank account Offset account type Offset account Method of payment Payment status Check number Payment request id&quot;i] >> internal:label=&quot;Payment status&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b43ad52a-e9b6-452a-8a36-666219c56b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTrans_PaymentStatus_735_0_0_input</value>
      <webElementGuid>08434807-af52-4214-bb98-fd182741d131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>bc420599-0ad9-4d0e-bca7-df920c991e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33554019-edcb-42bd-8879-40ab8c3dc7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7166832d-50c6-4487-9b97-011a7ecb5058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Payment status</value>
      <webElementGuid>9dddb7c3-de36-4e4c-a2d4-9a3a8172a08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _ezcqi5</value>
      <webElementGuid>3ffa28e8-009c-474f-9949-1191bb44f47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>1a212f50-a009-47d9-8902-4ae7665b1266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>92cb1191-6852-445e-a642-bbfb7e59cd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTrans_PaymentStatus_735_0_0_input&quot;)</value>
      <webElementGuid>e96c82c5-b126-4c4d-a970-f21bdaeb8c5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LedgerJournalTrans_PaymentStatus_735_0_0_input']</value>
      <webElementGuid>2187b13c-e47c-44d8-b742-48402383c151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTrans_PaymentStatus_735_0_0']/div/input</value>
      <webElementGuid>da54f7d2-eede-4de7-9854-f94cc4c6be1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/div/div/div/input</value>
      <webElementGuid>31a8ac71-b18f-4edb-b84b-3a61b85cf5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LedgerJournalTrans_PaymentStatus_735_0_0_input' and @type = 'text' and @title = 'Sent']</value>
      <webElementGuid>fc23089a-5239-4d30-a617-52e1d538731b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
