<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Journal batch numberNameDescriptionPost_f3d4c0</name>
   <tag></tag>
   <elementGuidId>caaf40be-4094-4011-8cb1-ed6656f4b810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='GridOverview_191_0_grid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GridOverview_191_0_grid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ledger journal table&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1dc800a0-cab5-4f3f-b402-c51ceb0b0959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_xyda97 fixedDataTableLayout_main public_fixedDataTable_main</value>
      <webElementGuid>dd8b7492-ef6b-45e7-bf59-70eaea147ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>grid</value>
      <webElementGuid>3e197cfd-a257-47d9-a67b-2019dcf3585d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-rowcount</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6b161654-ac0a-4172-a98e-2338ec570567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colcount</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>8bf2ef7c-429f-499f-8548-15166872429c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GridOverview_191_0_grid</value>
      <webElementGuid>0ba9906d-9842-4304-92b6-94234d91cc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98519060-6cec-400e-9082-91311ef8f78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ledger journal table</value>
      <webElementGuid>a53b549f-74ff-4cff-ad77-8d976f14ef3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8098d686-eac0-4a25-bca9-61fdd99f83bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Journal batch numberNameDescriptionPostedPosted onLogIn useIn use byModified byRejected by</value>
      <webElementGuid>1cfa45b2-3b3d-4e5c-aa43-7f39f97882f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GridOverview_191_0_grid&quot;)</value>
      <webElementGuid>9786191b-9a12-434e-98c6-eda24f48a3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='GridOverview_191_0_grid']</value>
      <webElementGuid>c44a2de8-1d08-4295-9cc3-3c1eab07225b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GridOverview_191_0']/div</value>
      <webElementGuid>0c4892f2-20e3-4e07-8518-6aeafd44381c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::div[7]</value>
      <webElementGuid>94d74730-c0cd-4991-8c20-223d975380af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial dimensions'])[1]/following::div[7]</value>
      <webElementGuid>c201d478-1aea-4b2c-8208-5bca935f7794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[3]/div/div/div/div/div</value>
      <webElementGuid>a72561b2-7fb6-4025-a7f7-b2a57df2734e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'GridOverview_191_0_grid' and (text() = 'Journal batch numberNameDescriptionPostedPosted onLogIn useIn use byModified byRejected by' or . = 'Journal batch numberNameDescriptionPostedPosted onLogIn useIn use byModified byRejected by')]</value>
      <webElementGuid>52296a7c-9c7d-4a66-9b22-ecfcbd24d01c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
