<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Journal batch numberNameDescriptionPost_f3d4c0_1</name>
   <tag></tag>
   <elementGuidId>a2105b01-5200-4ec8-8493-d47adcb37946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fixedDataTableLayout_rowsContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.fixedDataTableLayout_rowsContainer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc7d615d-3e1f-4881-a94c-b57fe06dc286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixedDataTableLayout_rowsContainer</value>
      <webElementGuid>adecc21f-0395-49e6-aa3b-5a84ed57b316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Journal batch numberNameDescriptionPostedPosted onLogIn useIn use byModified byRejected by</value>
      <webElementGuid>a6758d5a-a16b-4772-ba86-c9b566a36e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GridOverview_191_0_grid&quot;)/div[@class=&quot;fixedDataTableLayout_rowsContainer&quot;]</value>
      <webElementGuid>136594d2-415c-4d56-919f-d36a74f884b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GridOverview_191_0_grid']/div</value>
      <webElementGuid>321b5cb4-10d5-4f7d-bee7-eed8a21c59fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::div[8]</value>
      <webElementGuid>96ab8d90-18da-4dcb-baca-900fc401d707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial dimensions'])[1]/following::div[8]</value>
      <webElementGuid>61e0ef05-2ef7-46fc-b509-1023ef993b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>6c8b9d93-b33f-492f-aaed-d54b8fbb74ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Journal batch numberNameDescriptionPostedPosted onLogIn useIn use byModified byRejected by' or . = 'Journal batch numberNameDescriptionPostedPosted onLogIn useIn use byModified byRejected by')]</value>
      <webElementGuid>fa79753e-b367-4b76-9bd6-75ac5b37a093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
