<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rejected by_LedgerJournalTable_Journa_58aaa8</name>
   <tag></tag>
   <elementGuidId>559cf8e9-a949-4aac-a05f-75d9ecb2e135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTable_JournalNum_191_0_1_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;LedgerJournalTable_JournalNum_191_0_1_input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;00022
&#xd;
Click to follow link&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45300936-1bf9-472e-bfe8-70575e99d074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTable_JournalNum_191_0_1_input</value>
      <webElementGuid>1bc866c8-8fd8-4467-b3e2-063a4b8629d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>30a8b6b0-afbc-4630-994d-63c6f018a2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b55f2579-4213-45d9-bde9-10db81522754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01ac22c6-5951-42bd-9d28-f5d77d23d7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Journal batch number</value>
      <webElementGuid>3d6d947a-dc53-4d70-95ae-9b0cf62eedad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field dyn-hyperlink _nrrlfe</value>
      <webElementGuid>e40d34c9-d9fb-4cc3-be5e-ed2448c7decb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00022</value>
      <webElementGuid>c409e2d3-7fb4-4eff-9c5e-2ad71af5a89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-savedtooltip</name>
      <type>Main</type>
      <value>00022
&#xd;
Click to follow link</value>
      <webElementGuid>0242cbd0-26d1-4231-b650-57403505402e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>00022
&#xd;
Click to follow link</value>
      <webElementGuid>12ef0d2a-b59c-4b8e-b4ff-80c4bb9692f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3e9e7348-01fd-49a4-93b4-eddf73032ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTable_JournalNum_191_0_1_input&quot;)</value>
      <webElementGuid>6a9378d8-3e30-480e-95cc-b50c19468674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LedgerJournalTable_JournalNum_191_0_1_input']</value>
      <webElementGuid>864f2c9d-97ed-4b75-9b14-46a820a8761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTable_JournalNum_191_0_1']/div/input</value>
      <webElementGuid>4088e8ac-369f-4aae-a604-e858dd200654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>0c350893-e18b-48c9-8811-dd5950994cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LedgerJournalTable_JournalNum_191_0_1_input' and @type = 'text' and @title = '00022
&#xd;
Click to follow link']</value>
      <webElementGuid>6cd4f190-c144-441b-a518-072a22e1577a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
