<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rejected by_LedgerJournalTable_Journa_473124</name>
   <tag></tag>
   <elementGuidId>f068a726-fe5c-4b72-b0d6-5c6547df0a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LedgerJournalTable_JournalNum_3_0_1_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LedgerJournalTable_JournalNum_3_0_1_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;00022
&#xd;
Click to follow link&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cd8ce0c-ca4c-487a-b044-c6c5e177bb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LedgerJournalTable_JournalNum_3_0_1_input</value>
      <webElementGuid>3fee7c6d-9caa-4fc1-b67a-c4fe603a3177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>936d92fc-b6f1-4c6c-8848-0644cb1d8fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cd71452-27ad-45ef-8154-4a289a49ee89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a000f4ff-b563-4d9c-a976-eaa22f716775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Journal batch number</value>
      <webElementGuid>1ec6f76a-f3f0-4181-a866-43bdeb718ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field dyn-hyperlink _nrrlfe</value>
      <webElementGuid>6931d8a2-9dea-4a97-807e-bdd62f36405d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c0b1119c-312e-40e3-9a69-48fa46f6da23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00022</value>
      <webElementGuid>584dfbd9-dd76-4333-a210-925f3afc253a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-savedtooltip</name>
      <type>Main</type>
      <value>00022
&#xd;
Click to follow link</value>
      <webElementGuid>58dc4be7-e37c-4848-b738-5a03f6581987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>00022
&#xd;
Click to follow link</value>
      <webElementGuid>ea1bfb94-de9c-4a19-afba-673a1d663d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LedgerJournalTable_JournalNum_3_0_1_input&quot;)</value>
      <webElementGuid>88c94383-3d61-4207-976a-fd4eef78c8ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LedgerJournalTable_JournalNum_3_0_1_input']</value>
      <webElementGuid>f211910e-0ab6-4e77-bcfa-e250df7e4a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LedgerJournalTable_JournalNum_3_0_1']/div/input</value>
      <webElementGuid>187c2c6c-c93b-4b9a-a57b-8a8effc4fc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>b8cb5cad-9e0b-4e40-a5b6-4545b1eb4f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LedgerJournalTable_JournalNum_3_0_1_input' and @type = 'text' and @title = '00022
&#xd;
Click to follow link']</value>
      <webElementGuid>0008396d-af6e-47d7-abc8-0a481e668d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
