<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Posted_lookupButton</name>
   <tag></tag>
   <elementGuidId>73decc17-229c-4a1f-8934-259daacbc742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lookupDock-dockContainer.lookupDock-comboBox.displayoption.hasFocusedChild > div.lookupDock-buttonContainer.layout-ignoreArrange > div.lookupButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Posted'])[2]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#custfreeinvoicelistpage_6_AllOpenPostedField div >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11c845cf-06d1-4413-a2d7-6ae6762b2bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lookupButton</value>
      <webElementGuid>366ebc84-48f1-458c-a57c-9a552dbfd9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63b2dc27-51bc-4238-8e97-445a3695390f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f995d81c-74d1-4e5a-b64a-7a60074a679b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
                title: $dyn.label('Input_LookupTooltip'),
                superTooltip: $dyn.ui.superTooltip($data),
                attr: { 'data-dyn-helptext': $dyn.label('Input_LookupHelpText') },
                flyout: {
                    skipAria: true, flyout: $($element).parent().parent().find('.comboBox-list'), of: $($element).parent().parent(),
                    show: $data.isExpanded, positionResize: true, takeFocus: false, clickSubscriber: $data.flyoutClickSubscriber,
                    optOutOfWait: true, escapeSubscriber: $data.flyoutEscapeSubscriber
                }</value>
      <webElementGuid>b67ed44c-916d-4620-8bb8-e60e5e4f47d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>752c69cd-46e7-478c-a5dd-46af81ed9a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-helptext</name>
      <type>Main</type>
      <value>(Alt+Down)</value>
      <webElementGuid>609dce2a-599d-4f3a-8bba-1cde3f7b2315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-qtip-title</name>
      <type>Main</type>
      <value>Open</value>
      <webElementGuid>bec28e21-5034-466b-a81c-544552368f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-qtip-hastitleattr</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30f12931-8c21-4211-a274-866607358747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>264452c2-3ff4-4ba0-8458-fffd4ce677c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-0</value>
      <webElementGuid>1977bc56-6de1-4b7d-bfdf-aaf445d382b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custfreeinvoicelistpage_6_AllOpenPostedField&quot;)/div[@class=&quot;lookupDock-dockContainer lookupDock-comboBox displayoption hasFocusedChild&quot;]/div[@class=&quot;lookupDock-buttonContainer layout-ignoreArrange&quot;]/div[@class=&quot;lookupButton&quot;]</value>
      <webElementGuid>d37e5805-1bef-416e-8a35-705e4adca925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custfreeinvoicelistpage_6_AllOpenPostedField']/div/div[2]/div</value>
      <webElementGuid>61b6e407-8459-4537-8bce-4f970d1b36fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posted'])[2]/following::div[2]</value>
      <webElementGuid>804fd38f-a386-4c3b-b10b-623d8150d3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not posted'])[1]/following::div[2]</value>
      <webElementGuid>834f21a0-be7f-4eb1-befa-78c9db704ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice date'])[1]/preceding::div[1]</value>
      <webElementGuid>ebac148f-d275-4288-8838-93a58f73507f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='After the lookup is open, you can use Alt+Down to move focus into the lookup.'])[3]/preceding::div[1]</value>
      <webElementGuid>137db25c-ecc9-467e-8244-c0a2a78d4f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[3]/div/div[2]/div</value>
      <webElementGuid>97940fd2-cfc2-487e-a002-3452c6a087bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
