<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_After the lookup is open, you can use A_1eee2c_1_2</name>
   <tag></tag>
   <elementGuidId>d1e4a5a0-af84-4c77-8c7b-0740bdadda40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lookupDock-dockContainer.lookupDock-dateTime.displayoption.hasFocusedChild > div.lookupDock-buttonContainer.layout-ignoreArrange > div.lookupButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='custfreeinvoicelistpage_6_CustInvoiceTable_DueDateCV']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#custfreeinvoicelistpage_6_CustInvoiceTable_DueDateCV div >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f60fe6c-8039-446d-9a03-49eb4148f1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lookupButton</value>
      <webElementGuid>5b77513c-1d6c-4657-a640-6a8bf8a79dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc9bffc0-0d79-4f95-a13f-2d12cda92010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d3d72f7b-acc5-4a76-8c2b-f68f0ddae46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
                click: $data.showPicker,
                mouseDown: $data.checkPickerState,
                title: $dyn.label('Input_LookupTooltip'),
                superTooltip: $dyn.ui.superTooltip($data),
                attr: { 'data-dyn-helptext': $dyn.label('Input_LookupHelpText') }</value>
      <webElementGuid>0011631e-2f14-4faf-b7c7-4927bee0a426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-stop-binding</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97921782-3fa4-4101-837f-d7a7238406f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc7a6964-6dff-42d8-8202-efe88c7d4791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-helptext</name>
      <type>Main</type>
      <value>(Alt+Down)</value>
      <webElementGuid>94800574-1c4f-4f5d-836c-f3784d312fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-qtip-title</name>
      <type>Main</type>
      <value>Open</value>
      <webElementGuid>176e69c2-5667-4f42-9ae8-776ef2d92c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-qtip-hastitleattr</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22560f49-c0b7-4d83-b8ad-0ebbb924b3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>superToolTip</value>
      <webElementGuid>bd421f70-0f52-44b0-bf41-3e4a640f441e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-superToolTip</value>
      <webElementGuid>97edc8af-a269-4aa0-ba3d-26b4dfe57ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custfreeinvoicelistpage_6_CustInvoiceTable_DueDateCV&quot;)/div[@class=&quot;lookupDock-dockContainer lookupDock-dateTime displayoption hasFocusedChild&quot;]/div[@class=&quot;lookupDock-buttonContainer layout-ignoreArrange&quot;]/div[@class=&quot;lookupButton&quot;]</value>
      <webElementGuid>6bf26325-3bb9-4743-aa1b-be77b0b4fd1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custfreeinvoicelistpage_6_CustInvoiceTable_DueDateCV']/div/div[2]/div</value>
      <webElementGuid>d29f90aa-5f47-47c5-94a4-82fc3f9043c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='After the lookup is open, you can use Alt+Down to move focus into the lookup.'])[4]/following::div[2]</value>
      <webElementGuid>ea09ea55-db64-4c11-bc37-9c500524e05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due'])[1]/following::div[4]</value>
      <webElementGuid>e5a78ba3-5f54-4d97-b61b-e6823f914124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice'])[3]/preceding::div[2]</value>
      <webElementGuid>27710cab-dad6-4cfc-b8ec-77a1e6a404d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='After the lookup is open, you can use Alt+Down to move focus into the lookup.'])[5]/preceding::div[2]</value>
      <webElementGuid>0970347a-eaa6-448b-b766-962cecfe7a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div/div[2]/div</value>
      <webElementGuid>9beb7b5d-8d5d-47c4-a3cb-db81505d469b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
