<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_ValueColumn_12475_0_0_input</name>
   <tag></tag>
   <elementGuidId>37f45bb5-93c4-499e-b0fa-0b7d867c933f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValueColumn_12475_0_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValueColumn_12475_0_0_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;4533000&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da690ae4-957a-4b18-ba87-05b7749e027f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValueColumn_12475_0_0_input</value>
      <webElementGuid>9b908f50-3789-4dcb-8f50-99f07e73561f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>998d19e6-2d57-4e5b-9a3f-c59a84ea77a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f428fd8-c324-4e83-bfa9-9903a2edeea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>afac7cb7-8590-4c84-abbb-5ca44607d866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dimension value</value>
      <webElementGuid>289be0a6-30a8-47b3-ac5a-bc1857e2e745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>d26f7ade-3b89-4e93-9892-c96176c417ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>4533000</value>
      <webElementGuid>144b3599-544c-4ba0-b0a3-c40a50c8b0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4533000</value>
      <webElementGuid>12e4bdf0-b3d2-4149-8c55-7b68016ebbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValueColumn_12475_0_0_input&quot;)</value>
      <webElementGuid>08577566-6b4a-40c8-8ea6-58dabbb76e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValueColumn_12475_0_0_input']</value>
      <webElementGuid>8a0c0e14-711d-4a68-9cbb-c2f2b697e5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ValueColumn_12475_0_0']/div/input</value>
      <webElementGuid>f21568c6-61ce-4e54-9802-5a4002407d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>f0c2caa0-a21f-42cc-93a8-ec7bb7b1a3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ValueColumn_12475_0_0_input' and @type = 'text' and @title = '4533000']</value>
      <webElementGuid>f5aab28b-f723-4efe-92fb-1134bc655ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
