<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_SysGen_Name_12071_0_0_input</name>
   <tag></tag>
   <elementGuidId>9dc7d5a5-2442-44ac-a8d2-4d3dfaac239b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SysGen_Name_12071_0_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/div/div[3]/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Diensten - Geen BTW&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58d1a509-84a5-421c-8da3-fc6991970e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SysGen_Name_12071_0_0_input</value>
      <webElementGuid>255e31e7-a66d-4a96-8bb1-6629fda3969d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8b0921ff-ab98-4e43-96b6-cba48b825f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8817190-97bf-4e0f-9494-8d4ee8b03664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e097fc63-8230-4e05-a857-ecaee8882a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>7ea378eb-2ee1-4e8f-947e-746edb2592e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>95eb7c5b-cd0a-44ae-946c-afdbb3fe4628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Diensten - Geen BTW</value>
      <webElementGuid>04594fe1-f4fa-4940-a3f2-2378b5ce5d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Diensten - Geen BTW</value>
      <webElementGuid>972dea0d-be6e-4c03-8c17-3eb3a2da75f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SysGen_Name_12071_0_0_input&quot;)</value>
      <webElementGuid>4916e2ee-3d8b-457e-a72b-b5278f74ca9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SysGen_Name_12071_0_0_input']</value>
      <webElementGuid>b9bf08ab-0dfd-44e7-abc6-30393a69c7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SysGen_Name_12071_0_0']/div/input</value>
      <webElementGuid>1524a14e-53b7-4a67-ae32-c48b1df07b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>d1d83ce6-362c-460d-b4b3-5c1f58372a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SysGen_Name_12071_0_0_input' and @type = 'text' and @title = 'Diensten - Geen BTW']</value>
      <webElementGuid>ee2a4739-0255-415c-b998-138aa7f6ff2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
