<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Internally invoiced_CustInvoiceLine_T_bd02ff</name>
   <tag></tag>
   <elementGuidId>b33e7401-4c6b-40e2-9a7a-b63b51de8460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div[2]/div/div[4]/div/div/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CustInvoiceLine_TaxItemGroup_585_0_0_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Item sales tax group&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0faec7d7-f0ca-4287-b602-036b9a353a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustInvoiceLine_TaxItemGroup_585_0_0_input</value>
      <webElementGuid>1d7f28eb-acf0-4bfe-b5ed-8d7bac4e7592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2a45527b-be15-46b5-939f-fa895220ca5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>501f564d-c655-4bd6-9203-b1302ca32b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d134c3b-3f36-4916-803d-0c3d4f265adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Item sales tax group</value>
      <webElementGuid>ca6edda2-b204-4348-a1c9-85f42c5c27be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field dyn-hyperlink _1lamxtd</value>
      <webElementGuid>849c2958-9260-41d5-b12d-ab015be3fcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12393970-6ecf-4355-98b4-3a55d9f7f9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>2a71eb53-8df3-4496-8df2-007518e11b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>20fa2a6e-2d3c-4a14-8b4b-ab73f027b08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d9873cbd-d4de-402b-9832-aab0bdd05dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-savedtooltip</name>
      <type>Main</type>
      <value>
&#xd;
Click to follow link</value>
      <webElementGuid>fda27026-3094-4549-89ba-e6cc68c50b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-previewenabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d97129ac-e00a-4429-9e58-be76dd4915f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustInvoiceLine_TaxItemGroup_585_0_0_input&quot;)</value>
      <webElementGuid>98de8c14-d244-4e74-8d05-0c99d2b1cbf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustInvoiceLine_TaxItemGroup_585_0_0_input']</value>
      <webElementGuid>852cb30f-ab11-49d9-b5ae-386c9c138654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustInvoiceLine_TaxItemGroup_585_0_0']/div/input</value>
      <webElementGuid>63db6218-02e7-4fef-849c-2f9a609bbdcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div[4]/div/div/div/div/div/div/input</value>
      <webElementGuid>a1e01853-9c7f-4285-b535-800666edc526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CustInvoiceLine_TaxItemGroup_585_0_0_input' and @type = 'text']</value>
      <webElementGuid>4b7e7172-e543-49d7-b3f4-f1058429c8f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
