<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account number_DirPartyTable_Name_116_19ff68</name>
   <tag></tag>
   <elementGuidId>9a1c3c8a-49e4-402e-acc4-dffb82bf56ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirPartyTable_Name_1168_0_3_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DirPartyTable_Name_1168_0_3_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DirPartyTable_Name_1168_0_3_input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>247022e5-5186-4713-a142-fc5331332a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirPartyTable_Name_1168_0_3_input</value>
      <webElementGuid>79c41b35-5f72-4929-a8a6-f8475eacb98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>aff25441-12ce-4954-a315-77e6607c7f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59599f83-3fe0-47e5-bdb8-a0e4a852bb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3694c6b-c2c5-4800-91a4-a6e8db46e62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>a06ff339-e8d7-47bf-a77e-fb886c46c777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>56f46b32-b18b-4f4a-b130-ceb35bd1f5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BIENSTMAN NIENKE</value>
      <webElementGuid>0d6aa306-d274-4494-a381-2150ac78d4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b41faaa0-35ff-43b6-9430-0c595b45b73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BIENSTMAN NIENKE</value>
      <webElementGuid>86c82bfe-a71a-4e7b-847e-055d03346e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirPartyTable_Name_1168_0_3_input&quot;)</value>
      <webElementGuid>e6d10931-909d-46b6-96a1-64c125fe13eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DirPartyTable_Name_1168_0_3_input']</value>
      <webElementGuid>9d4adfa6-4dee-437e-ba66-688ea39d843c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirPartyTable_Name_1168_0_3']/div/input</value>
      <webElementGuid>a423f730-25a8-420e-a784-36a8fce03a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div[4]/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>34ade4a5-02d2-4893-b0bd-67d0cffe1346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DirPartyTable_Name_1168_0_3_input' and @type = 'text' and @title = 'BIENSTMAN NIENKE']</value>
      <webElementGuid>f7e82ac3-14ad-43f3-9bc3-c91447108959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
