<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Internally invoiced_CustInvoiceLine_L_14343b</name>
   <tag></tag>
   <elementGuidId>cd90e6d9-077d-4e32-aab7-d0ad5a3b2b8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustInvoiceLine_LedgerAccount_0_segmentedEntryLookup_input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'CustInvoiceLine_LedgerAccount_0_segmentedEntryLookup_input' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CustInvoiceLine_LedgerAccount_0_segmentedEntryLookup_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Main account&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23bd16a7-a879-4269-b439-afb7da4ccbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustInvoiceLine_LedgerAccount_0_segmentedEntryLookup_input</value>
      <webElementGuid>31e11bd7-2d6c-4d90-8622-e363875f8eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>b208ba15-9c48-439e-a038-913dff81687c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>405fb46e-f30d-4feb-bac1-7309974e4b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1dc108a2-6a6d-4c36-a105-84efc3e94718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main account</value>
      <webElementGuid>a01643a3-7cbb-46be-a458-f779422f8aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>713b41fd-0c43-4486-83dd-4f4a6c86a65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32436413-d64c-459c-ac1c-ba6228a838eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>6f73427b-8409-4d22-838f-7a90392a3963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ddc5d08-81f3-42ed-89a3-3fe7afb0eaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a28e7df2-662e-425a-9da1-cbc6b1bccff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustInvoiceLine_LedgerAccount_0_segmentedEntryLookup_input&quot;)</value>
      <webElementGuid>d59bc822-0312-4f82-aa30-7f5b7c02b264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustInvoiceLine_LedgerAccount_0_segmentedEntryLookup_input']</value>
      <webElementGuid>2e3c890f-fc38-4b3a-9206-19b7051138ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustInvoiceLine_LedgerAccount_0_segmentedEntryLookup']/div/input</value>
      <webElementGuid>2e7c0787-a760-46c1-8f70-9e90d2a89f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>9f05b9e2-860a-4f94-bdd0-07676200e12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CustInvoiceLine_LedgerAccount_0_segmentedEntryLookup_input' and @type = 'text']</value>
      <webElementGuid>640e1be8-0aa5-46e0-a247-4b645e19f8f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
