<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Internally invoiced_CustInvoiceLine_U_87a09a</name>
   <tag></tag>
   <elementGuidId>f68c2efb-dd1c-41aa-a86f-402af08d67f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustInvoiceLine_UnitPrice_585_0_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustInvoiceLine_UnitPrice_585_0_0_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Unit price&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3d84993-7613-4971-855c-2f98a38a586a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustInvoiceLine_UnitPrice_585_0_0_input</value>
      <webElementGuid>1873fec8-5a34-4587-b03a-0eb88b3d4796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>244ca488-6755-4312-a102-c7a339011ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ece4a82f-1d7b-4e02-9a92-284eaf1f845f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>becb4b78-bd89-41f4-b0be-1952eadcb9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Unit price</value>
      <webElementGuid>e0936439-3664-429c-857e-f692a7bbadef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _iijgt8</value>
      <webElementGuid>753b36c7-8a0a-4a4b-806e-f4af1315907f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0a95241-97fc-402b-b330-b20706be732b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0acd8cc9-26cb-4e6c-b94a-21c03f2a12c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustInvoiceLine_UnitPrice_585_0_0_input&quot;)</value>
      <webElementGuid>553add18-7b72-4068-a461-24434b9d15f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustInvoiceLine_UnitPrice_585_0_0_input']</value>
      <webElementGuid>7a31c15e-5e8c-4486-bda6-fd0a23bfde95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustInvoiceLine_UnitPrice_585_0_0']/div/input</value>
      <webElementGuid>00d883c0-c415-4330-bb70-c2712498d925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/input</value>
      <webElementGuid>65c06f17-f80d-4f6d-ac7a-8d98cd217b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CustInvoiceLine_UnitPrice_585_0_0_input' and @type = 'text']</value>
      <webElementGuid>e84fabe4-dd66-484e-885f-3f833571defb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
