<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Internally invoiced_CustInvoiceLine_U_fe4247</name>
   <tag></tag>
   <elementGuidId>de8933a5-3379-42e3-bc5d-7676889b43a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustInvoiceLine_UnitPrice_487_0_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustInvoiceLine_UnitPrice_487_0_0_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Unit price&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e0a72ea-d731-4e6d-b62b-c377e8db82a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustInvoiceLine_UnitPrice_487_0_0_input</value>
      <webElementGuid>2619db47-054c-42d4-904b-132083b50a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9fe680f0-b9e9-4286-a64d-3446c032a599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b526f500-5547-4bfd-b45f-b004055233c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>08fdb78a-3764-4c3f-8efc-c8b761f4dcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Unit price</value>
      <webElementGuid>7164b85c-c94a-4dd7-a0fa-bffd8559bea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _iijgt8</value>
      <webElementGuid>2d4b8b91-eead-404b-b1ad-56afaddcec14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>56ce8e58-441b-4ed0-9e14-c0391f6b4292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d2328e04-6663-46f3-9709-ac790fa71932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustInvoiceLine_UnitPrice_487_0_0_input&quot;)</value>
      <webElementGuid>cfcbbf80-f214-4df0-9e5b-dafa7bd48c89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustInvoiceLine_UnitPrice_487_0_0_input']</value>
      <webElementGuid>21118160-49b8-4032-acd9-354f201b928e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustInvoiceLine_UnitPrice_487_0_0']/div/input</value>
      <webElementGuid>19adcaf6-69b7-4be9-8281-df9d13ad2797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/input</value>
      <webElementGuid>5345b7e4-d743-462a-b58f-378e70ab277a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CustInvoiceLine_UnitPrice_487_0_0_input' and @type = 'text']</value>
      <webElementGuid>fcbc9306-cd70-4060-aa99-52996c577cf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
