<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_Id_0_input</name>
   <tag></tag>
   <elementGuidId>09f23e71-b149-4353-a671-68610880972c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Id_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Id_0_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Value&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a51883f8-c580-4f38-94ed-c2d64e5d017f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Id_0_input</value>
      <webElementGuid>b3725f84-40e7-47dc-aada-a206635376da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>63c6254c-b894-48a7-9c3b-bff666d97985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed41df72-4ca8-4330-884a-f7d34262872a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0886968c-3085-4438-b0ed-25d2efaefd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>653b69df-eeae-4595-bc37-14a2b2a01d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>9c3cc479-0eb3-4a37-a570-9b41e96f718c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>7003020000</value>
      <webElementGuid>da8bbfd4-47ef-4a49-8acf-98550236228a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7003020000</value>
      <webElementGuid>70133c31-64c3-45a9-809c-b08b00732a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Id_0_input&quot;)</value>
      <webElementGuid>083c05ac-71e2-425b-af4a-d71e27ac6b4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Id_0_input']</value>
      <webElementGuid>e70e7585-afbc-46bb-8b94-6bb43fa4198e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Id_0']/div/input</value>
      <webElementGuid>16244190-e5ed-4f26-895a-a9847f46fcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>374b4218-576e-4c20-9ee0-c63785b5cba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Id_0_input' and @type = 'text' and @title = '7003020000']</value>
      <webElementGuid>7fd2d955-d451-483d-8775-add8dd203a85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
