<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , DataArea_id_32_1_0_inpu_53ddef</name>
   <tag></tag>
   <elementGuidId>2abd3f03-fb50-447e-a954-b9304bb2e8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DataArea_id_32_1_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DataArea_id_32_1_0_input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65b8cb62-bc44-47a8-83b5-58c8fe62dc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataArea_id_32_1_0_input</value>
      <webElementGuid>330b49b5-7b91-4d9c-875a-992b097a665b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>01ee18aa-4875-411a-9b47-fda4accf7afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99d3f7f0-22f1-44e7-87db-0a38608062a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8cd02edf-32c8-4306-8876-61f6281294b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>6f3e05b8-7219-4adc-8727-9ed6b04b9fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>bda4a5be-6f7d-4c63-83e6-a2b4102b1014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BEH</value>
      <webElementGuid>2c000508-70cf-428c-86bb-05572737546a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-savedtooltip</name>
      <type>Main</type>
      <value>BEH</value>
      <webElementGuid>30a6cf2a-f416-419b-9504-7dcbe21baa19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-previewenabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>870f2fc6-8ffe-4925-bcae-50fa15a8f42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataArea_id_32_1_0_input&quot;)</value>
      <webElementGuid>2d0ce777-f0ca-44f3-8957-f50e22c2a100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataArea_id_32_1_0_input']</value>
      <webElementGuid>674b7b31-01c7-41e4-a70e-71e9665af78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataArea_id_32_1_0']/div/input</value>
      <webElementGuid>c46a93af-394f-40e3-b73a-e01f9c9d0a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>19b3202f-3ee1-45b0-b40a-9dad6e45985a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataArea_id_32_1_0_input' and @type = 'text']</value>
      <webElementGuid>6791f6ef-ee8f-439f-ae1d-0fe485d2695a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
