<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Internally invoiced_CustInvoiceLine_D_493258</name>
   <tag></tag>
   <elementGuidId>705a0fa3-6a86-4a2e-9e2b-3d7faaa89847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustInvoiceLine_Description_585_0_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustInvoiceLine_Description_585_0_0_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29a6dcf6-733f-4d63-baf7-5add21d715c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustInvoiceLine_Description_585_0_0_input</value>
      <webElementGuid>1cf5b236-6836-43bb-8779-b73bfec817dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b4204a7a-c61b-4b56-bf72-40a9dff55223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0fb4495-3eab-49c3-8202-12d0d889dc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a52be05-26b1-4b75-8fe9-0f3a84d8e236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>abf701e9-154b-4be9-955d-17c52b72d2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>bcbe2bc6-2ab8-48b0-9e22-41b81d2a1740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>64b7119c-a8e0-4516-b318-07506d0e2be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8436ed9a-3d3c-421a-8ac1-3aba599a1cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aca162c6-03a9-4a15-b251-017388ff12ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustInvoiceLine_Description_585_0_0_input&quot;)</value>
      <webElementGuid>43036925-7529-463b-9498-8128664726ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustInvoiceLine_Description_585_0_0_input']</value>
      <webElementGuid>c8aa60a0-7aaf-467b-8341-3829496093f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustInvoiceLine_Description_585_0_0']/div/input</value>
      <webElementGuid>53764079-8cd2-478d-9bc7-9a7f7f491553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>3916102f-004f-420f-bb5b-99d749ed6606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CustInvoiceLine_Description_585_0_0_input' and @type = 'text']</value>
      <webElementGuid>a61b377c-6422-4480-a71b-1a28f8709e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
