<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account number_DirPartyTable_Name_671_556b0e</name>
   <tag></tag>
   <elementGuidId>91b45c0b-b541-41cb-80dd-f7555513650c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirPartyTable_Name_6716_0_3_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/div/div[3]/div[4]/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DirPartyTable_Name_6716_0_3_input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2485751-8392-4064-a228-52036af2907a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirPartyTable_Name_6716_0_3_input</value>
      <webElementGuid>ecf02695-3f9e-463a-bf22-8032a8d7db75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a3fd25a4-2b73-401e-a2e6-59bc3ee50d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>942663d5-c9e5-4e72-8593-df6354f94b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1513c38-776e-46e4-acdf-8061d6a69245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>d601e250-2c9d-4553-822e-196b80798f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>1e23f718-3f15-4d3a-a8dd-bc36a94715ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BIENSTMAN NIENKE</value>
      <webElementGuid>e585ead8-9f65-402d-8817-2ef13ce85bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>09b2b32d-e4e4-4917-8afc-2365a58f0269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BIENSTMAN NIENKE</value>
      <webElementGuid>607d2745-cbcd-49cb-ae83-9cc612a9f1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirPartyTable_Name_6716_0_3_input&quot;)</value>
      <webElementGuid>f2512fec-876a-4625-808c-d3332f789bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DirPartyTable_Name_6716_0_3_input']</value>
      <webElementGuid>3c2eaa7c-cf9b-410c-94e6-2856fbcd9a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirPartyTable_Name_6716_0_3']/div/input</value>
      <webElementGuid>47783881-f5c3-4385-909c-6e4829523e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div[4]/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>e11a6732-f87a-434d-aaed-78669507f224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DirPartyTable_Name_6716_0_3_input' and @type = 'text' and @title = 'BIENSTMAN NIENKE']</value>
      <webElementGuid>99bb498a-8c13-4ae9-8ceb-b624b5ebe575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
