<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , DataArea_name_16_1_0_in_40d020</name>
   <tag></tag>
   <elementGuidId>b70a2ad4-aaa4-4b90-a3bd-4257b299c72b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DataArea_name_16_1_0_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DataArea_name_16_1_0_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be666bd3-26b7-4625-864b-f27e615135a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataArea_name_16_1_0_input</value>
      <webElementGuid>e733635b-5a6c-4e53-8ea3-5a91b47966b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c5e418fc-8fd2-4c3e-acb8-016c1c56a646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37b2c8d3-b823-4038-ad07-28bfc2c71edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c21d12fb-638d-4f57-b3f9-20f87311aa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Company name</value>
      <webElementGuid>4ed4a235-c54f-4622-82c4-68aebb1ed2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _1o6vy5b</value>
      <webElementGuid>03b221b6-ef19-47c7-b0b8-833f08bda6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bedrijfsopleidingen</value>
      <webElementGuid>07abd409-6af7-4ddf-ae3b-fb547dd13da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Bedrijfsopleidingen</value>
      <webElementGuid>54c4d62a-8980-44dc-a27f-a540ff70db8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataArea_name_16_1_0_input&quot;)</value>
      <webElementGuid>0ea35d24-62d1-41a1-8ea3-e46dec21efca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataArea_name_16_1_0_input']</value>
      <webElementGuid>d604e0c8-c620-434c-9a51-1dfb658a77e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataArea_name_16_1_0']/div/input</value>
      <webElementGuid>eeb62fc6-c481-4886-b0fd-8da1108ef360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>f2ec250d-29f7-47b3-8d14-d84016e0bad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataArea_name_16_1_0_input' and @type = 'text' and @title = 'Bedrijfsopleidingen']</value>
      <webElementGuid>a2ace78e-b999-4b28-a3e6-b8b968300a36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
