<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account number_DirPartyTable_Name_499_7cc48c</name>
   <tag></tag>
   <elementGuidId>72fa14be-6009-4f9b-8bd6-ab78b2bc9bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirPartyTable_Name_4993_0_3_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DirPartyTable_Name_4993_0_3_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DirPartyTable_Name_4993_0_3_input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddf0cd65-649a-48ad-be76-77521b7d5e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirPartyTable_Name_4993_0_3_input</value>
      <webElementGuid>9422ea4a-b0f1-4d50-8ae3-e3bb513128ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ccbbe951-11e1-4df2-902a-92ec101508f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69382bb8-86d5-4fad-8adc-1ff6f0f269d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d83ff04-9370-4c44-88b0-0010973f2d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>ae3a93c7-232b-4d03-8a92-bd597aa5ded9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>3346a5a1-aba8-49a2-8cb0-b8567f57c793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BIENSTMAN NIENKE</value>
      <webElementGuid>4ef9bffb-6e86-4af0-b593-c042badd550d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d6ad4d0e-8336-47eb-a6e6-f0d28dc75505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BIENSTMAN NIENKE</value>
      <webElementGuid>bc1afd61-9c83-4b88-8f6b-8f00a5f9474c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirPartyTable_Name_4993_0_3_input&quot;)</value>
      <webElementGuid>baf65924-d3c3-4b36-9197-c23cb6c1f464</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DirPartyTable_Name_4993_0_3_input']</value>
      <webElementGuid>aec79e47-39a8-416f-94d7-d3eaad1be4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirPartyTable_Name_4993_0_3']/div/input</value>
      <webElementGuid>fd6d1226-7cde-4cab-a95e-0fd3c6720098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div[4]/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>f170b6cc-9b58-4223-bfd4-09ef60250ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DirPartyTable_Name_4993_0_3_input' and @type = 'text' and @title = 'BIENSTMAN NIENKE']</value>
      <webElementGuid>1517333c-5cc9-45ff-a6e6-60f764dcc0d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
