<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account number_DirPartyTable_Name_128_81bb22</name>
   <tag></tag>
   <elementGuidId>d60ff27c-faca-4f69-ae18-94c7e228d01e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirPartyTable_Name_12880_0_2_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DirPartyTable_Name_12880_0_2_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DirPartyTable_Name_12880_0_2_input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>069b0e20-a598-4cae-874e-be3a86409e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirPartyTable_Name_12880_0_2_input</value>
      <webElementGuid>16bd3103-359b-4552-9a93-ff78330dd136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2c4dda61-7659-4fc4-8827-7b25b6b8c699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6403c468-9768-462a-8227-b139852cd601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d917c723-56d8-4dc8-ae5d-4081f519c00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>ba96756a-84a3-41d5-a55a-94247ca542e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>0a3dcb11-2bd4-4892-a143-dfffdc6bf3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>VAN EYKEN ANN</value>
      <webElementGuid>f39d6ae2-ceba-4041-9cc4-1a22b61690b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>68dfecfd-6ebd-4ee4-9a33-c842ec1237e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>VAN EYKEN ANN</value>
      <webElementGuid>40c3ad26-d745-43fb-9a7b-a7399898aef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirPartyTable_Name_12880_0_2_input&quot;)</value>
      <webElementGuid>433f1681-7eea-404c-9096-38c5daaec1e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DirPartyTable_Name_12880_0_2_input']</value>
      <webElementGuid>cd13ca1e-0232-41c7-be04-209917e0a7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirPartyTable_Name_12880_0_2']/div/input</value>
      <webElementGuid>ee10afb5-c8c4-4989-8b38-b9df384842a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>7c781e8d-8b45-4d22-b947-c3cda56ef381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DirPartyTable_Name_12880_0_2_input' and @type = 'text' and @title = 'VAN EYKEN ANN']</value>
      <webElementGuid>c045a151-7fcb-4204-bfea-db23e8e154c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
