<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account number_DirPartyTable_Name_780_8c9db1</name>
   <tag></tag>
   <elementGuidId>a3516e7a-583a-4bdf-a8f6-537464950bfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirPartyTable_Name_7802_0_3_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DirPartyTable_Name_7802_0_3_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DirPartyTable_Name_7802_0_3_input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a80b612-6272-4c16-854d-741fd012209c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirPartyTable_Name_7802_0_3_input</value>
      <webElementGuid>f9d4d903-2123-4702-8068-32a90cd7c118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>80e262f4-86ba-40e7-920a-98ec1d1428e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6684db1-f07b-43ec-9677-23a25c105bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>42de8e57-613c-4448-a530-9613184b52b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>77d5daaa-c797-4204-abf2-170d302830ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _7gf207</value>
      <webElementGuid>62306a3b-5938-4d06-b5af-5910e80f7836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BIENSTMAN NIENKE</value>
      <webElementGuid>78050158-6e1a-458b-8733-c4a49b0daacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BIENSTMAN NIENKE</value>
      <webElementGuid>be3d6e5e-a713-4386-9d6d-13102c8a3d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirPartyTable_Name_7802_0_3_input&quot;)</value>
      <webElementGuid>d424d633-efbc-47bf-8ab7-e8e75ff335dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DirPartyTable_Name_7802_0_3_input']</value>
      <webElementGuid>1de6574c-25de-4625-8f8f-6b374196cc6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DirPartyTable_Name_7802_0_3']/div/input</value>
      <webElementGuid>73c11388-7811-487b-9808-8aa67b547450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div[4]/div/div/div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>804937bc-f8d5-4a8e-96b2-29d39d717e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DirPartyTable_Name_7802_0_3_input' and @type = 'text' and @title = 'BIENSTMAN NIENKE']</value>
      <webElementGuid>897a2520-0e08-4407-924f-646746b54b7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
