<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_All</name>
   <tag></tag>
   <elementGuidId>9eab7c2a-d71c-46fe-94a0-f7732e4791a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custfreeinvoicelistpage_6_AllOpenPostedField_list_item0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Not posted'])[1]/preceding::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;All&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7e5451ec-ea28-4f48-a0b6-51a0a8cd8b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7c77d297-89b5-41d6-a78a-7aa2987b7fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
                    id: $parent().Id + '_list_item' + $index,
                    text: $data.Label,
                    showLabel: { Label: $data.Label, AllowBlankLabel: true },
                    superTooltip: $dyn.ui.superTooltip($data),
                    attr: { 'aria-selected': $dyn.value($parent().listShownIndex) == $index },
                    click: { callBack: function () { $parent().clickedItem($index); }, stopPropagation: true }</value>
      <webElementGuid>70e772b1-39a2-4a43-94d0-cc906910dd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-stop-binding</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>004b16b0-d6ab-455a-8fc9-0a2333503811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custfreeinvoicelistpage_6_AllOpenPostedField_list_item0</value>
      <webElementGuid>ccaae470-5452-4e6e-aa18-3cc9ef19237f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-lastvisible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c16d00c-1da8-45c9-8b30-019a7020a74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d21576a2-936a-44e5-89f2-49e5ef5e77c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b99c755-5d84-4f71-a5d7-234858daae1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9181094a-1767-489c-bed1-3dcaefd19491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>3dcee1fd-8821-44e3-8e87-58fb465003aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custfreeinvoicelistpage_6_AllOpenPostedField_list_item0&quot;)</value>
      <webElementGuid>2234a6ca-c5cd-41c9-8a94-215adfb6596d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='custfreeinvoicelistpage_6_AllOpenPostedField_list_item0']</value>
      <webElementGuid>b840791b-4eca-4008-b0ad-e6f823c01b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='custfreeinvoicelistpage_6_AllOpenPostedField_list']/li</value>
      <webElementGuid>b585307d-e412-4998-8b2b-ea4c629c7226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not posted'])[1]/preceding::li[1]</value>
      <webElementGuid>f18b107d-5969-4cc2-a0e6-0bea9e31eb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posted'])[3]/preceding::li[2]</value>
      <webElementGuid>2c8877cd-e0d9-4bb6-967d-84a9b93256f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>6f8acdf6-7bc5-498c-9e4f-38c97cded26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li</value>
      <webElementGuid>34c5ddb1-010a-4e52-95bd-68647ed4f71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'custfreeinvoicelistpage_6_AllOpenPostedField_list_item0' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>35215880-5d6c-49f4-a663-24e8e4b8ea5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
