<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Custom</name>
   <tag></tag>
   <elementGuidId>96b75b8c-f59d-4cca-b1a4-9adcb95b50c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custfreeinvoicelistpage_6_FilterInvoiceDate_list_item3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Custom']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Custom&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f69ed1da-2de1-4a3d-81aa-9e6f1d9bc374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ec6a1899-7dc8-4d2d-8486-6d50b05ff2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
                    id: $parent().Id + '_list_item' + $index,
                    text: $data.Label,
                    showLabel: { Label: $data.Label, AllowBlankLabel: true },
                    superTooltip: $dyn.ui.superTooltip($data),
                    attr: { 'aria-selected': $dyn.value($parent().listShownIndex) == $index },
                    click: { callBack: function () { $parent().clickedItem($index); }, stopPropagation: true }</value>
      <webElementGuid>36fff795-e333-48f7-9bb9-6c0421555f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-stop-binding</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bcae5f26-a946-4882-bb09-99f6cdc24e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custfreeinvoicelistpage_6_FilterInvoiceDate_list_item3</value>
      <webElementGuid>bca8b117-e5e0-4fc0-ac6e-fc830fb75a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-lastvisible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8429ec58-6c09-4f2e-a2a1-8032dbc94bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>790496f3-7eb2-4a6a-ae81-326724acddb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82cdcd3b-883f-4c0c-9ae3-93d8dc42689b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>21375005-0439-42ac-8598-4340e28c9945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Custom</value>
      <webElementGuid>ca87cac5-e032-49eb-8011-3cc1fc8e2f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custfreeinvoicelistpage_6_FilterInvoiceDate_list_item3&quot;)</value>
      <webElementGuid>9a72246c-af1a-42d7-b794-004f80a3ce52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='custfreeinvoicelistpage_6_FilterInvoiceDate_list_item3']</value>
      <webElementGuid>c7fbcb57-142e-4e7a-9f8a-c3ef8578c8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='custfreeinvoicelistpage_6_FilterInvoiceDate_list']/li[4]</value>
      <webElementGuid>c2e8964e-ce53-4f93-b3cb-ae5d180e78b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Custom']/parent::*</value>
      <webElementGuid>5b8ddb55-89da-42c6-a755-a67658e504f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[4]</value>
      <webElementGuid>a17f1d50-e429-4872-8640-b0f855db5d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'custfreeinvoicelistpage_6_FilterInvoiceDate_list_item3' and (text() = 'Custom' or . = 'Custom')]</value>
      <webElementGuid>6fb3d7d5-cac2-4fcc-9c44-0645f46eeefa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
