<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Original</name>
   <tag></tag>
   <elementGuidId>f89fb087-988f-41c9-9d5a-c979e47464df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custfreeinvoicelistpage_5_ViewOriginal_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='custfreeinvoicelistpage_5_ViewOriginal_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Original&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ac16f2f-8233-4abe-bf2d-9135ae229aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-label</value>
      <webElementGuid>c89b522b-952d-4632-b934-c446c3a929c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
            id: $data.Id + '_label',
            ariaLabelFor: $dyn.ui.ariaLabelFor($data.Id, $data, $data.Label),
            attr: { 'aria-describedby': $dyn.ui.getDescribedByData($data) }</value>
      <webElementGuid>cc1da189-bfd3-46a7-86df-fd3d58ff3cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custfreeinvoicelistpage_5_ViewOriginal_label</value>
      <webElementGuid>b23c7d6c-54da-4aff-83ec-fff03d4d1074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>custfreeinvoicelistpage_5_ViewOriginal</value>
      <webElementGuid>7649cd13-0abd-40d7-8f33-54a3cfbb6991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>custfreeinvoicelistpage_5_ViewOriginal_helptext</value>
      <webElementGuid>02b34143-778f-4d07-8db2-c65c83059464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Original</value>
      <webElementGuid>9236cf44-337e-4431-bbe7-074084739a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custfreeinvoicelistpage_5_ViewOriginal_label&quot;)</value>
      <webElementGuid>1072bb45-bfd6-4c38-ac37-0a651b500ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='custfreeinvoicelistpage_5_ViewOriginal_label']</value>
      <webElementGuid>9749f238-78db-4911-b402-b65c685cd1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='custfreeinvoicelistpage_5_ViewOriginal']/div/span[3]</value>
      <webElementGuid>133311f5-bebd-4059-abdf-e1f362ae25c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/following::span[3]</value>
      <webElementGuid>038d32bc-9ec9-4e52-82f0-0572529b48d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Original']/parent::*</value>
      <webElementGuid>07128519-c535-4313-bbbd-f22852b0002f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/button[2]/div/span[3]</value>
      <webElementGuid>c13ba811-aa98-4327-8768-7e8589b64311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'custfreeinvoicelistpage_5_ViewOriginal_label' and (text() = 'Original' or . = 'Original')]</value>
      <webElementGuid>dc8ffb3f-5d0a-44e7-bac2-cf0fbc168c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
